"""Recreate the paper's BG107 cumulative patch-count curve from time_data.json.

By default, emit the plotted points as JSON. A .png or .pdf output additionally
requires matplotlib; JSON generation has no third-party dependencies.
"""

import argparse
import json
from pathlib import Path
import random


HERE = Path(__file__).resolve().parent
LABELS = {
    "Rete": r"$\mathcal{V}^{S}_{R(S, C)}$",
    "CoCoNut": r"$\mathcal{V}^{C}_{C}$",
    "Prophet": r"$\mathcal{V}^{P}_{P}$",
}


def curves(time_data, repetitions=10, seed=454364, days=16):
    if set(time_data) != set(LABELS):
        raise ValueError(f"expected timing series for {', '.join(LABELS)}")
    if any(len(times) != 107 for times in time_data.values()):
        raise ValueError("each timing series must contain 107 BG107 entries")
    if any(not isinstance(t, (int, float)) or t < 0
           for times in time_data.values() for t in times):
        raise ValueError("timings must be nonnegative numbers")
    permutation = list(range(107))
    rng = random.Random(seed)
    totals = {tool: [0] * days for tool in LABELS}
    for _ in range(repetitions):
        rng.shuffle(permutation)
        for tool, times in time_data.items():
            cumulative = 0
            found_at = []
            for index in permutation:
                cumulative += times[index]
                if times[index] < 240:
                    found_at.append(cumulative / (24 * 60))
            for day in range(1, days + 1):
                totals[tool][day - 1] += sum(t <= day for t in found_at)
    return {tool: [count / repetitions for count in counts]
            for tool, counts in totals.items()}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=HERE / "time_data.json")
    parser.add_argument("--output", type=Path,
                        help="write .json, .png or .pdf; default prints JSON")
    args = parser.parse_args(argv)
    with args.data.open(encoding="utf-8") as stream:
        data = json.load(stream)
    result = {"days": list(range(1, 17)), "mean_patches": curves(data)}
    if args.output is None:
        print(json.dumps(result, indent=2))
    elif args.output.suffix.lower() == ".json":
        args.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    elif args.output.suffix.lower() in (".png", ".pdf"):
        import matplotlib.pyplot as plt
        for tool, values in result["mean_patches"].items():
            plt.plot(result["days"], values, label=LABELS[tool])
        plt.xticks(result["days"])
        plt.xlabel("Time in days")
        plt.ylabel("Number of patches")
        plt.title("Patches generated by each tool")
        plt.legend()
        plt.savefig(args.output, bbox_inches="tight")
    else:
        parser.error("--output must end in .json, .png or .pdf")


if __name__ == "__main__":
    main()
