import matplotlib.pyplot as plt
import math
import string




patch_count_C = {
    "$T^S_{R(S, F)}$": [4, 6, 6, 6, 6, 6],
    "$T^E_T$": [2, 3 ,3 ,3, 4, 6],
}
xint = list(range(0, 60, 10))
yint = list(range(1, 7))
plt.xticks(xint)
yint = list(range(0, 35, 5))
plt.yticks(yint)

for key, val in patch_count_C.items():
    plt.plot(patch_count_C[key], label = key)



plt.xlabel('Time in days')
plt.ylabel('Number of Patches')

plt.title('Patches generated by each tool')

plt.legend()

plt.show()

