import matplotlib.pyplot as plt
import math
import string
import random
import itertools
import json

random.seed(3524634)
x = [i for i in range(1, 17)]

with open("time_data.json", 'r') as f:
    lis = json.load(f)

permut_list = list(range(0, 107))
random.seed(454364)
patch_find_time = {
    "$\mathcal{V}^{S}_{R(S, C)}$": [],
    "$\mathcal{V}^{C}_{C}$": [],
    "$\mathcal{V}^{P}_{P}$": []
}
keys = {
    "Rete": "$\mathcal{V}^{S}_{R(S, C)}$",
    "CoCoNut": "$\mathcal{V}^{C}_{C}$",
    "Prophet": "$\mathcal{V}^{P}_{P}$"
}

for i in range(10):
    random.shuffle(permut_list)
    for tool, times in lis.items():
        cumulative = 0
        found_time = []
        for i in permut_list:
            cumulative += times[i]
            if times[i] < 240: found_time.append(cumulative/(24*60))
        patch_find_time[keys[tool]].append(found_time)

for key, vals in patch_find_time.items():
    plt.xticks(x)
    yint = list(range(0, 35, 5))
    plt.yticks(yint)
    y = [0]*16
    for val in vals:
        for i in range(1, 17):
            y[i - 1] += len([time for time in val if time <= i])
    y = [i/10 for i in y]
            
    plt.plot(x, y, label = key)



plt.xlabel('Time in days')
plt.ylabel('Number of Patches')

plt.title('Patches generated by each tool')

plt.legend()

plt.show()
